config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'

  devise_for :users

    root 'articles#index'

  get '/articles' => 'articles#index', as: 'articles'
  get '/articles/new' => 'articles#new', as: 'new_article'
  post '/articles' => 'articles#create'
  get '/articles/:id' => 'articles#show', as: 'article'

  get '/articles/:id/edit' => 'articles#edit', as: 'edit_article'
  post '/articles/:id' => 'articles#update'
  get '/articles/:id/delete' => 'articles#destroy', as: 'delete' 
  
  get 'home' => 'articles#index', as: 'home'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
    if params[:_method].present?
      #@articles = current_user.articles
      @articles = current_user.articles.paginate(:page => params[:page], :per_page => 3)
    else
      #@articles = Article.all
      @articles = Article.paginate(:page => params[:page], :per_page => 3)
    end
    
  end

  def show
    #@article = Article.find(params[:id])
    @articles = Article.paginate(:page => params[:page], :per_page => 3)
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = current_user.articles.new(article_params)
    #@article = Article.new(article_params)
    #@article.user_id = current_user.id
    @article.save
    # redirect_to articles_path
    #@articles = Article.all
     @articles = Article.paginate(:page => params[:page], :per_page => 3)
  end

  def update
      @article = Article.find(params[:id])
 
    if @article.update(article_params)
      #redirect_to articles_path
      #@articles = Article.all
      @articles = Article.paginate(:page => params[:page], :per_page => 3)
    else
      render 'edit'
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end
    
private
  def article_params
    params.require(:article).permit(:user_id, :title, :text, :post_type)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_edit.html.erb
<tbody width="600"> 
  
  <%= form_for :article, url: article_path(@article), method: :post, :remote => true do |f| %>
  <tr class = 'tid', id = "tid-<%=@article.id%>" >
    <td>
      <%= @article.user_id %>
    </td>  
    <td>
      <%= @article.id %>
    </td>
   
    <td>
      <%= f.text_field :title %>
    </td>

    <td>
      <%= f.text_area :text %>
    </td>
    
    <td>
      <%= @article.post_type %>
    </td>
   
    <td>
      <%= f.submit 'Save' %>
    </td>
    
  </tr>
  <% end %>
</tbody>

app/views/articles/_edit_post.html.erb
<div class="container">
<h2>Editing Post!!</h2>

<%= form_for :article, url: article_path(@article), method: :post, :remote => true do |f| %>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.label :post_type %>
    <%= f.select :post_type, [['Friends','Friends'],['Only Me','Only Me'],['Public','Public']] %>
    
 </p>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
</div>

app/views/articles/_index_post.html.erb
<div class="container">
<h2>
Welcome <%= current_user.email %> !!
<%= link_to 'LogOut', destroy_user_session_path, :method => :delete %>
</h2>

<h3>
<%= link_to 'Home', home_path, method: :get %>
<%= link_to 'All Post', articles_path %>
<%= link_to 'New Post', new_article_path, :remote => true %> 
</h3>
 
 <h2>Listing articles</h2>
<table class="table table-bordered">
 <thead>
  <tr>
    <th>User Id</th>
    <th>Article Id</th>
    <th>Title</th>
    <th>Text</th>
    <th>Post Type</th>
  </tr>
 </thead>
 <tbody>
  <% @articles.each do |article| %>
    <tr class = 'tid', id = "tid-<%=article.id%>" >
      <td><%= article.user_id %></td>
      <td><%= article.id %></td>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= article.post_type %></td>
      
      <td><%= link_to 'Show', article_path(article), :remote => true %></td>
      <td><%= link_to 'Edit', edit_article_path(article), :remote => true %></td>
      <td><%= link_to 'Destroy', delete_path(article),
              method: :get,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/articles/_new_post.html.erb
<div class="container">
<h2>New Post!!</h2>

<%= form_for :article, :url => {'action' => 'create'}, :remote =>true do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, :id => 'txttittle' %>
  </p>
 
  <p>
    <%= f.label :text %>
    <%= f.text_area :text, :id => 'txtarea' %>
  </p>
 <p>
    <%= f.label :post_type %>
    <%= f.select :post_type, [['Friends','Friends'],['Only Me','Only Me'],['Public','Public']] %>
    
 </p>
  <p>
    <%= f.submit :id => "btnsubmit" %>
  </p>
<% end %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
      $("#btnsubmit").click(function(){
        if($("#txttittle").val() == "")
        {
          alert("Enter Tittle");
          $("#txttittle").focus();
          return false;
        }
        if($("#txtarea").val() == "")
        {
          alert("Enter Text");
          $("#txtarea").focus();
          return false;
        }
      });
  })
</script>

app/views/articles/_show_post.html.erb
<div class="container">
<h2>You have Posted!!</h2>
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<p>
	<strong>Post Type:</strong>
	<%= @article.post_type %>
</p>
</div>

app/views/articles/create.js.erb
$("#index_post").html("<%= j render(:partial => 'index_post') %>");
$("#div_crud").html("<%= j render(:partial => 'show_post') %>");

// $("#new_post").html("")
// $("#show_post").html("<%= j render(:partial => 'show_post') %>")
// $("#edit_post").html("")

app/views/articles/edit.html.erb
<h2>Editing Post!!</h2>

<%= form_for :article, url: article_path(@article), method: :post do |f| %>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.label :post_type %>
    <%= f.select :post_type, [['Friends','Friends'],['Only Me','Only Me'],['Public','Public']] %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/edit.js.erb
$("#div_crud").html("<%= j render(:partial => 'edit_post') %>");

// $("#tid-<%=@article.id%>").html("<%= j render(:partial => 'edit') %>");

// $("#edit_post").html("<%= j render(:partial => 'edit_post')%>");
// $("#new_post").html("")
// $("#show_post").html("")

app/views/articles/index.html.erb
<div id="index_post">
  <%= render :partial => "articles/index_post" %>
  
</div>

<div id="div_crud"></div>

<%= will_paginate @articles %>
<!-- <div id="show_post"></div> -->

<!-- <div id="new_post"></div> -->

<!-- <div id="edit_post"></div> -->

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, :url => {'action' => 'create'} do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.label :post_type %>
    <%= f.select :post_type, [['Friends','Friends'],['Only Me','Only Me'],['Public','Public']] %>
 </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/new.js.erb
$("#div_crud").html("<%= j render(:partial => 'new_post') %>");

// $("#new_post").html("<%= j render(:partial => 'new_post')%>");
// $("#show_post").html("");
// $("#edit_post").html("");

app/views/articles/show.html.erb
<h2>You have Posted!!</h2>
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
	<strong>Post Type:</strong>
	<%= @article.post_type %>
</p>

<%= link_to 'Back', articles_path %>

app/views/articles/show.js.erb
$("#div_crud").html("<%= j render(:partial => 'show_post') %>");

// $("#show_post").html("<%= j render(:partial => 'show_post') %>");
// $("#new_post").html("")
// $("#edit_post").html("")

app/views/articles/update.js.erb
 $("#index_post").html("<%= j render(:partial => 'index_post') %>");
  $("#div_crud").html("<%= j render(:partial => 'show_post') %>");

// $("#tid-<%=@article.id%>").html("<%= j render(:partial => 'index_post') %>");

// $("#new_post").html("")
// $("#show_post").html("<%= j render(:partial => 'show_post') %>")
// $("#edit_post").html("")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="container">
<%= yield %>
</div>

</body>
</html>